{% set name = "pretend" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c90eb810cde8ebb06dafcb8796f9a95228ce796531bc806e794c2f4649aa1b10

build:
  number: 2
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pretend
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/alex/pretend
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: A library for stubbing in Python
  description: A library to make stubbing with Python easier.
  dev_url: https://github.com/alex/pretend
  doc_url: https://github.com/alex/pretend

extra:
  recipe-maintainers:
    - CJ-Wright
    - sodre
