travis:
  secure:
    BINSTAR_TOKEN: S5FtfrbTx35m6N6CApuVLwkBSyOp67FLsM09fQCsKigStu79LJv1WAksCATuOvxo4wwaqkZNlOEQApIxj/9KxNFDXnRHo4bVPubvh1Jk7RaWGOwD6Abq7g0j4VxPKYw52EvjZzp9f3lIwLRUEaFkexNUrWpMObPOYHgm/z0waZqJRKCESMVG10dc6utTc56l+s7wR7DkcUFDZISNCyOlgySPpH1iFf6d1AGxDGIDdcQTQscwksMfjk22AVBQPXMZ3/tufbuh4GAU8tBMT9+Agv6iCL0ByGwPC8FrzYz+rTMWnmodiHyC+5PzWwd87jenDosQU7XUQn3xb5pxJapL3CyORq1F2HYU7ewTV5VvS1Bm1j29e5+RMlP5E5AhGKA+pTkVNDXR15/dtkWLFGwoHjL85zGX7JdwVmnxvfvowsUl2CKOKHaB4JVRel8azsDfulJA1NLKf/51iS+aPjgq7bbguXogP9bn/UfNmexjb5O2m88sIXH+CjaELmvodswHMTkswhhTmpY2i2Snb8t3lhHzOfRAVKzCy6ik5tmCXM+o+eyNtzV8R3lMdvjSFofzrIQ89Zn/a8epMT5l6WkOdZMNa4Quzt9h9rgjgy9g3u41TmSJwxE0YbYplDVmUyTiBoaNFPsrHy4sNaFgeoxCypvKjoWrqSTwbYnINgPFYoE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
